services:
  postgres:
    image: postgres:alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-task_manager_db}
      POSTGRES_USER: ${POSTGRES_USER:-task_manager_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: django-container
    restart: always
    depends_on:
      - postgres
    environment:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
